CREATE TABLE VIOLATIONS (
VEHICLE_NUMBER VARCHAR(255) PRIMARY KEY,
VIOLATION_TYPE VARCHAR(255),
VIOLATION_DATE DATE,
FINE_AMOUNT  DOUBLE,
PAID_AMOUNT DOUBLE,
ACTIVE_IND VARCHAR(255)
);

CREATE TABLE VEHICLE (
VEHICLE_NUMBER VARCHAR(255) PRIMARY KEY,
OWNER_NAME VARCHAR(255),
PURCHASE_DATE DATE,
COLOR  VARCHAR(255),
MAKE VARCHAR(255),
VEHICLE_PLATE_NUMBER VARCHAR(255)
);

ALTER TABLE VIOLATIONS
ADD FOREIGN KEY (VEHICLE_NUMBER) REFERENCES VEHICLE(VEHICLE_NUMBER);